services:
  - type: web
    name: habit-tracker-api
    env: node
    buildCommand: npm ci --include=dev && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.11.1
# Add your SharePoint or other secrets as additional envVars if needed
