services:
  - type: web
    name: habit-tracker-fullstack
    env: node  
    region: oregon
    plan: free
    buildCommand: npm run install:all && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.11.1
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: USE_MOCK_DATA
        value: false
      # SharePoint Configuration (set these in Render dashboard)
      # - key: SHAREPOINT_SITE_ID
      #   sync: false
      # - key: SHAREPOINT_HABITS_LIST_ID  
      #   sync: false
      # - key: SHAREPOINT_USERS_LIST_ID
      #   sync: false
      # - key: MICROSOFT_TENANT_ID
      #   sync: false
      # - key: MICROSOFT_CLIENT_ID
      #   sync: false
      # - key: MICROSOFT_CLIENT_SECRET
      #   sync: false
